universe = vanilla

executable = /afs/cern.ch/user/m/matheus/CMSSW_10_6_23/src/simulation_steps.sh

output = output/$(ClusterId)_$(ProcId).out
error  = output/$(ClusterId)_$(ProcId).err
log    = output/$(ClusterId)_$(ProcId).log

getenv     = True

environment = "X509_USER_PROXY=/afs/cern.ch/user/m/matheus/x509up_u130329"

requirements = (OpSysAndVer =?= "CentOS7")

request_memory = 32000

+JobFlavour = "nextweek"

request_cpus = 4
transfer_input_files=/afs/cern.ch/user/m/matheus/CMSSW_10_6_23/src/simulation_steps.sh, /afs/cern.ch/user/m/matheus/CMSSW_10_6_23/src/gensim_digi_step.py, /afs/cern.ch/user/m/matheus/CMSSW_10_6_23/src/reco_step.py, /afs/cern.ch/user/m/matheus/CMSSW_10_2_16_UL/src/hlt_step.py
should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

queue arguments from /afs/cern.ch/user/m/matheus/CMSSW_10_6_23/src/ListFile_condor.txt